#!/bin/sh

ODIR=$1
NDIR=$2
FILES=`cat $3`

for i in $FILES; do
  FROM=$ODIR/$i
  TO=$NDIR/$i

  if cmp -s $FROM $TO; then
    FOO=bar
  else

    echo "FromFile: " $FROM `wc -c -l $FROM`
    echo "ToFile:   " $TO `wc -c -l $TO`

    # 1
    echo "Tool: cim"

    ./mytime cim-forward ../exact-delta/delta $FROM $TO > tmp.out
    echo "Normal: " `cat tmp.out`
    ./mytime cim-reverse ../exact-delta/delta $TO $FROM > tmp.out
    echo "Reverse: " `cat tmp.out`

    # 2
    echo "Tool: vdelta"

    ./mytime vdelta-forward ../vdelta $FROM < $TO > tmp.out
    echo "Normal: " `wc -c tmp.out`
    ./mytime vdelta-reverse ../vdelta $TO < $FROM > tmp.out
    echo "Reverse: " `wc -c tmp.out`

    # 3
    echo "Tool: xdelta"

    ./mytime xdelta-forward ../../../xdelta delta -0 -n $FROM $TO tmp.out
    echo "Normal: " `wc -c tmp.out`
    ./mytime xdelta-reverse ../../../xdelta delta -0 -n $TO $FROM tmp.out
    echo "Reverse: " `wc -c tmp.out`

    # 4
    echo "Tool: xz"

    ./mytime xz-forward ../../../xdelta delta -n $FROM $TO tmp.out
    echo "Normal: " `wc -c tmp.out`
    ./mytime xz-reverse ../../../xdelta delta -n $TO $FROM tmp.out
    echo "Reverse: " `wc -c tmp.out`

    # 5
    echo "Tool: diff"

    ./mytime diff-forward gdiff --rcs -a $FROM $TO > tmp.out
    echo "Normal: " `wc -c tmp.out`
    ./mytime diff-reverse gdiff --rcs -a $TO $FROM > tmp.out
    echo "Reverse: " `wc -c tmp.out`

    # 6
    echo "Tool: dz"

    ./mytime dz1-forward gdiff --rcs -a $FROM $TO > tmp.out
    rm -f tmp.out.gz
    ./mytime dz2-forward gzip tmp.out
    echo "Normal: " `wc -c tmp.out.gz`
    ./mytime dz1-reverse gdiff --rcs -a $TO $FROM > tmp.out
    rm -f tmp.out.gz
    ./mytime dz2-reverse gzip tmp.out
    echo "Reverse: " `wc -c tmp.out.gz`

  fi
done
