/* config.h generated by CMake.  See also configure.ac for the
   autotools-based build, which generates an equivalent header. */
#ifndef XDELTA3_CONFIG_H
#define XDELTA3_CONFIG_H

#define SIZEOF_SIZE_T @SIZEOF_SIZE_T@
#define SIZEOF_UNSIGNED_INT @SIZEOF_UNSIGNED_INT@
#define SIZEOF_UNSIGNED_LONG @SIZEOF_UNSIGNED_LONG@
#define SIZEOF_UNSIGNED_LONG_LONG @SIZEOF_UNSIGNED_LONG_LONG@

/* Defined to 1 when <lzma.h> and liblzma are available. */
#cmakedefine HAVE_LZMA_H 1

/* Defined when the target requires naturally-aligned memory access. */
#cmakedefine HAVE_ALIGNED_ACCESS_REQUIRED 1

#endif /* XDELTA3_CONFIG_H */
