#!/usr/bin/ksh
#
# Changed configure to install in /usr/local/lib/glib-1.2.
#
# Script was contributed by Klaus Dittrich

gmake distclean
CC="cc -Ae" \
CFLAGS="+O2 +Onolimit +DAportable" \
CPPFLAGS="-I/usr/local/include/glib-1.2 -I/usr/local/include/zlib" \
LDFLAGS="-L/usr/local/lib/glib-1.2 -L/usr/local/lib/zlib -lz" ./configure

gmake
gmake check
exit
:> ./TIME
sleep 1
gmake install
mkdir -p /usr/local/docs/glib
find /usr/local/* -newer ./TIME | grep -v `pwd` > THIS_WAS_INSTALLED
gmake distclean
